In [7]:
import numpy as np

In [8]:
def nonlinear(x,deriv=False):
    if deriv:
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [9]:
#input data
X_train = np.array([
        [0,0,1],
        [0,1,1],
        [1,0,1],
        [1,1,1],
    ])

#outputa data
Y_train = np.array([
        [0],
        [1],
        [1],
        [0],
    ])
print X_train.shape
print Y_train.shape

(4, 3)
(4, 1)


In [10]:
np.random.seed(1)

In [41]:
#synapses
syn0 = 2*np.random.random((3,4))-1
syn1 = 2*np.random.random((4,1))-1
print syn0
print syn1

[[-0.75165337 -0.44163264  0.17151854  0.9391915 ]
 [ 0.12206044 -0.96270542  0.60126535 -0.53405145]
 [ 0.61421039 -0.22427871  0.72708371  0.49424329]]
[[ 0.11248047]
 [-0.72708955]
 [-0.88016462]
 [-0.75731309]]


In [ ]:
for ix in range(300000):
    
    l0 = X_train
    l1 = nonlinear(np.dot(l0,syn0))
    l2 = nonlinear(np.dot(l1,syn1))
    
    l2_error = Y_train- l2

        
    l2_delta = l2_error*nonlinear(l2,deriv=True)
    l1_error = l2_delta.dot(syn1.T)
    l1_delta = l1_error*nonlinear(l1,deriv=True)
    

    syn1 = l1.T.dot(l2_delta)
    syn0 = l0.T.dot(l1_delta)
    
    if(ix%10000)==0:
        print syn0
        print syn1
        print l2
        print l2_error
        print "Error: " + str(np.mean(l2_error))

print "Output After Training"
print l2 
print Y_train

[[ -4.25085462e-05  -4.14098124e-05  -4.13285099e-05  -4.14139354e-05]
 [ -4.25085498e-05  -4.14098156e-05  -4.13285139e-05  -4.14139382e-05]
 [ -8.50316501e-05  -8.28347766e-05  -8.26702895e-05  -8.28418067e-05]]
[[ 0.006442  ]
 [ 0.0064457 ]
 [ 0.00643983]
 [ 0.00644134]]
[[ 0.48708863]
 [ 0.48709321]
 [ 0.48709321]
 [ 0.48709779]]
[[-0.48708863]
 [ 0.51290679]
 [ 0.51290679]
 [-0.48709779]]
Error: 0.0129067922294
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]]
[[ 0.5]
 [ 0.5]
 [ 0.5]
 [ 0.5]]
[[-0.5]
 [ 0.5]
 [ 0.5]
 [-0.5]]
Error: 0.0
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]]
[[ 0.5]
 [ 0.5]
 [ 0.5]
 [ 0.5]]
[[-0.5]
 [ 0.5]
 [ 0.5]
 [-0.5]]
Error: 0.0
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]]
[[ 0.5]
 [ 0.5]
 [ 0.5]
 [ 0.5]]
[[-0.5]
 [ 0.5]
 [ 0.5]
 [-0.5]]
Error: 0.0
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]]
[